FROM node

# COPY TASKS AND UTILS DIRS TO CONTAINER
ADD ./tasks /tasks/
ADD ./utils /utils/

# COPY WORKER TO CONTAINER
COPY ./worker.js /worker.js

# INSTALL DEPS
COPY ./package.json /package.json
RUN npm install

# SET CMD TO START WORKER
CMD node /worker.js
