apiVersion: batch/v1
kind: Job
metadata:
  name: worker
spec:
  parallelism: 6
  template:
    metadata:
      name: worker
    spec:
      containers:
      - name: workerc
        image: gcr.io/[PROJECT_ID]/worker
      restartPolicy: Never
